python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist jet_kin --savetag hadmu --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_eta --varlabel '$\eta(jet)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist jet_kin --savetag hadmu --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist lep_kin --savetag hadmu --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var miso --varlabel '$miniIso(\mu)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist lep_kin --savetag hadmu --xlimits None 0.1 --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lsf3 --varlabel '$LSF_{3}(\mu)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist lep_kin --savetag hadmu --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist jet_kin --savetag hadel --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_eta --varlabel '$\eta(jet)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist jet_kin --savetag hadel --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(e)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist lep_kin --savetag hadel --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var miso --varlabel '$miniIso(e)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist lep_kin --savetag hadel --xlimits None 0.1 --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lsf3 --varlabel '$LSF_{3}(e)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist lep_kin --savetag hadel --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist mass_kin --savetag hadmu --sigsel genhtt 2.5 3.5 --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jetmet_m --varlabel '$m(jet+MET)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist mass_kin --savetag hadmu --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jetlepmet_m --varlabel '$m(jet+lep+MET)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist mass_kin --savetag hadmu --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist mass_kin --savetag hadel --sigsel genhtt 1.5 2.5 --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jetmet_m --varlabel '$m(jet+MET)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist mass_kin --savetag hadel --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jetlepmet_m --varlabel '$m(jet+lep+MET)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist mass_kin --savetag hadel --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var met_pt --varlabel '$MET$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist evt_kin --savetag hadmu --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var met_pt --varlabel '$MET$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist evt_kin --savetag hadel --dosigrat
 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var oppbjet_pt --varlabel '$p_{T}(opp. b-jet)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist b_kin --savetag hadmu --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var oppbtag --varlabel '$Max Opp. deepCSV-b$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist b_kin --savetag hadmu --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var oppbjet_pt --varlabel '$p_{T}(opp. b-jet)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist b_kin --savetag hadel --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var oppbtag --varlabel '$Max Opp. deepCSV-b$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist b_kin --savetag hadel --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_jet_dr --varlabel '$\Delta R(jet,\mu)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist lep_kin --savetag hadmu --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_jet_dr --varlabel '$\Delta R(jet,e)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist lep_kin --savetag hadel --dosigrat
 --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h} ~bCR$' --lumi 36.7 --regions hadmu_cr_b --hist jet_kin --savetag hadmu_cr_b --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_eta --varlabel '$\eta(jet)$' --title '$\mu\tau_{h} ~bCR$' --lumi 36.7 --regions hadmu_cr_b --hist jet_kin --savetag hadmu_cr_b --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\mu\tau_{h} ~bCR$' --lumi 36.7 --regions hadmu_cr_b --hist lep_kin --savetag hadmu_cr_b --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var miso --varlabel '$miniIso(\mu)$' --title '$\mu\tau_{h} ~bCR$' --lumi 36.7 --regions hadmu_cr_b --hist lep_kin --savetag hadmu_cr_b --xlimits None 0.1 --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lsf3 --varlabel '$LSF_{3}(\mu)$' --title '$\mu\tau_{h} ~bCR$' --lumi 36.7 --regions hadmu_cr_b --hist lep_kin --savetag hadmu_cr_b --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h} ~bCR$' --lumi 36.7 --regions hadel_cr_b --hist jet_kin --savetag hadel_cr_b --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_eta --varlabel '$\eta(jet)$' --title '$e\tau_{h} ~bCR$' --lumi 36.7 --regions hadel_cr_b --hist jet_kin --savetag hadel_cr_b --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(e)$' --title '$e\tau_{h} ~bCR$' --lumi 36.7 --regions hadel_cr_b --hist lep_kin --savetag hadel_cr_b --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var miso --varlabel '$miniIso(e)$' --title '$e\tau_{h} ~bCR$' --lumi 36.7 --regions hadel_cr_b --hist lep_kin --savetag hadel_cr_b --xlimits None 0.1 --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lsf3 --varlabel '$LSF_{3}(e)$' --title '$e\tau_{h} ~bCR$' --lumi 36.7 --regions hadel_cr_b --hist lep_kin --savetag hadel_cr_b --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$\mu\tau_{h} ~bCR$' --lumi 36.7 --regions hadmu_cr_b --hist jet_kin --savetag hadmu_cr_b --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jetmet_m --varlabel '$m(jet+MET)$' --title '$\mu\tau_{h} ~bCR$' --lumi 36.7 --regions hadmu_cr_b --hist mass_kin --savetag hadmu_cr_b --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jetlepmet_m --varlabel '$m(jet+lep+MET)$' --title '$\mu\tau_{h} ~bCR$' --lumi 36.7 --regions hadmu_cr_b --hist mass_kin --savetag hadmu_cr_b --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$e\tau_{h} ~bCR$' --lumi 36.7 --regions hadel_cr_b --hist jet_kin --savetag hadel_cr_b --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jetmet_m --varlabel '$m(jet+MET)$' --title '$e\tau_{h} ~bCR$' --lumi 36.7 --regions hadel_cr_b --hist mass_kin --savetag hadel_cr_b --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jetlepmet_m --varlabel '$m(jet+lep+MET)$' --title '$e\tau_{h} ~bCR$' --lumi 36.7 --regions hadel_cr_b --hist mass_kin --savetag hadel_cr_b --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var met_pt --varlabel '$MET$' --title '$\mu\tau_{h} ~bCR$' --lumi 36.7 --regions hadmu_cr_b --hist evt_kin --savetag hadmu_cr_b --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var met_pt --varlabel '$MET$' --title '$e\tau_{h} ~bCR$' --lumi 36.7 --regions hadel_cr_b --hist evt_kin --savetag hadel_cr_b --dosigrat
##### --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist jet_kin --savetag hadmu_cr_qcd --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_eta --varlabel '$\eta(jet)$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist jet_kin --savetag hadmu_cr_qcd --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist lep_kin --savetag hadmu_cr_qcd --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var miso --varlabel '$miniIso(\mu)$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist lep_kin --savetag hadmu_cr_qcd --xlimits 0.1 None --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lsf3 --varlabel '$LSF_{3}(\mu)$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist lep_kin --savetag hadmu_cr_qcd --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist jet_kin --savetag hadel_cr_qcd --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_eta --varlabel '$\eta(jet)$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist jet_kin --savetag hadel_cr_qcd --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(e)$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist lep_kin --savetag hadel_cr_qcd --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var miso --varlabel '$miniIso(e)$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist lep_kin --savetag hadel_cr_qcd --xlimits 0.1 None --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lsf3 --varlabel '$LSF_{3}(e)$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist lep_kin --savetag hadel_cr_qcd --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist jet_kin --savetag hadmu_cr_qcd --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jetmet_m --varlabel '$m(jet+MET)$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist mass_kin --savetag hadmu_cr_qcd --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jetlepmet_m --varlabel '$m(jet+lep+MET)$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist mass_kin --savetag hadmu_cr_qcd --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist jet_kin --savetag hadel_cr_qcd --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jetmet_m --varlabel '$m(jet+MET)$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist mass_kin --savetag hadel_cr_qcd --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jetlepmet_m --varlabel '$m(jet+lep+MET)$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist mass_kin --savetag hadel_cr_qcd --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var met_pt --varlabel '$MET$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist evt_kin --savetag hadmu_cr_qcd --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var met_pt --varlabel '$MET$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist evt_kin --savetag hadel_cr_qcd --dosigrat
 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\tau_{h}\tau_{h}$' --lumi 36.7 --regions hadhad_signal --hist jet_kin --savetag hadhad --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_eta --varlabel '$\eta(jet)$' --title '$\tau_{h}\tau_{h}$' --lumi 36.7 --regions hadhad_signal --hist jet_kin --savetag hadhad --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$\tau_{h}\tau_{h}$' --lumi 36.7 --regions hadhad_signal --hist mass_kin --savetag hadhad --sigsel genhtt 0.5 1.5 --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jetmet_m --varlabel '$m(jet+MET)$' --title '$\tau_{h}\tau_{h}$' --lumi 36.7 --regions hadhad_signal --hist mass_kin --savetag hadhad --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var met_pt --varlabel '$MET$' --title '$\tau_{h}\tau_{h}$' --lumi 36.7 --regions hadhad_signal --hist evt_kin --savetag hadhad --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var oppbjet_pt --varlabel '$p_{T}(opp. b-jet)$' --title '$\tau_{h}\tau_{h}$' --lumi 36.7 --regions hadhad_signal --hist b_kin --savetag hadhad --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var oppbtag --varlabel '$Max Opp. deepCSV-b$' --title '$\tau_{h}\tau_{h}$' --lumi 36.7 --regions hadhad_signal --hist b_kin --savetag hadhad --dosigrat
 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\tau_{h}\tau_{h}~t\bar{t}~CR~\mu$' --lumi 36.7 --regions hadhad_cr_mu --hist jet_kin --savetag hadhad_cr_mu --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_eta --varlabel '$\eta(jet)$' --title '$\tau_{h}\tau_{h}~t\bar{t}~CR~\mu$' --lumi 36.7 --regions hadhad_cr_mu --hist jet_kin --savetag hadhad_cr_mu --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\tau_{h}\tau_{h}~t\bar{t}~CR~\mu$' --lumi 36.7 --regions hadhad_cr_mu --hist lep_kin --savetag hadhad_cr_mu --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$\tau_{h}\tau_{h}~t\bar{t}~CR~\mu$' --lumi 36.7 --regions hadhad_cr_mu --hist jet_kin --savetag hadhad_cr_mu --dosigrat
#python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jetmet_m --varlabel '$m(jet+MET)$' --title '$\tau_{h}\tau_{h}~t\bar{t}~CR~\mu$' --lumi 36.7 --regions hadhad_cr_mu --hist mass_kin --savetag hadhad_cr_mu --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var met_pt --varlabel '$MET$' --title '$\tau_{h}\tau_{h}~t\bar{t}~CR~\mu$' --lumi 36.7 --regions hadhad_cr_mu --hist evt_kin --savetag hadhad_cr_mu --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var oppbjet_pt --varlabel '$p_{T}(opp. b-jet)$' --title '$\tau_{h}\tau_{h}~t\bar{t}~CR~\mu$' --lumi 36.7 --regions hadhad_cr_mu --hist b_kin --savetag hadhad_cr_mu --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var oppbtag --varlabel '$Max Opp. deepCSV-b$' --title '$\tau_{h}\tau_{h}~t\bar{t}~CR~\mu$' --lumi 36.7 --regions hadhad_cr_mu --hist b_kin --savetag hadhad_cr_mu --dosigrat
 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$\mu\tau_{h},~300<p_{T}(j)<350$' --lumi 36.7 --regions hadmu_signal --hist mass_kin --savetag hadmu_jet_pt_300_350 --sel jet_pt neginf 350. --sigsel genhtt 2.5 3.5 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$e\tau_{h},~300<p_{T}(j)<350$' --lumi 36.7 --regions hadel_signal --hist mass_kin --savetag hadel_jet_pt_300_350 --sel jet_pt neginf 350. --sigsel genhtt 1.5 2.5 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$\tau_{h}\tau_{h},~300<p_{T}(j)<350$' --lumi 36.7 --regions hadhad_signal --hist mass_kin --savetag hadhad_jet_pt_300_350 --sel jet_pt neginf 350. --sigsel genhtt 0.5 1.5 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$\mu\tau_{h},~350<p_{T}(j)<400$' --lumi 36.7 --regions hadmu_signal --hist mass_kin --savetag hadmu_jet_pt_350_400 --sel jet_pt 350. 400. --sigsel genhtt 2.5 3.5 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$e\tau_{h},~350<p_{T}(j)<400$' --lumi 36.7 --regions hadel_signal --hist mass_kin --savetag hadel_jet_pt_350_400 --sel jet_pt 350. 400. --sigsel genhtt 1.5 2.5 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$\tau_{h}\tau_{h},~350<p_{T}(j)<400$' --lumi 36.7 --regions hadhad_signal --hist mass_kin --savetag hadhad_jet_pt_350_400 --sel jet_pt 350. 400. --sigsel genhtt 0.5 1.5 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$\mu\tau_{h},~400<p_{T}(j)<500$' --lumi 36.7 --regions hadmu_signal --hist mass_kin --savetag hadmu_jet_pt_400_500 --sel jet_pt 400. 500. --sigsel genhtt 2.5 3.5 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$e\tau_{h},~400<p_{T}(j)<500$' --lumi 36.7 --regions hadel_signal --hist mass_kin --savetag hadel_jet_pt_400_500 --sel jet_pt 400. 500. --sigsel genhtt 1.5 2.5 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$\tau_{h}\tau_{h},~400<p_{T}(j)<500$' --lumi 36.7 --regions hadhad_signal --hist mass_kin --savetag hadhad_jet_pt_400_500 --sel jet_pt 400. 500. --sigsel genhtt 0.5 1.5 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$\mu\tau_{h},~500<p_{T}(j)<600$' --lumi 36.7 --regions hadmu_signal --hist mass_kin --savetag hadmu_jet_pt_500_600 --sel jet_pt 500. 600. --sigsel genhtt 2.5 3.5 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$e\tau_{h},~500<p_{T}(j)<600$' --lumi 36.7 --regions hadel_signal --hist mass_kin --savetag hadel_jet_pt_500_600 --sel jet_pt 500. 600. --sigsel genhtt 1.5 2.5 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$\tau_{h}\tau_{h},~500<p_{T}(j)<600$' --lumi 36.7 --regions hadhad_signal --hist mass_kin --savetag hadhad_jet_pt_500_600 --sel jet_pt 500. 600. --sigsel genhtt 0.5 1.5 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$\mu\tau_{h},~600<p_{T}(j)<800$' --lumi 36.7 --regions hadmu_signal --hist mass_kin --savetag hadmu_jet_pt_600_800 --sel jet_pt 600. 800. --sigsel genhtt 2.5 3.5 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$e\tau_{h},~600<p_{T}(j)<800$' --lumi 36.7 --regions hadel_signal --hist mass_kin --savetag hadel_jet_pt_600_800 --sel jet_pt 600. 800. --sigsel genhtt 1.5 2.5 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$\tau_{h}\tau_{h},~600<p_{T}(j)<800$' --lumi 36.7 --regions hadhad_signal --hist mass_kin --savetag hadhad_jet_pt_600_800 --sel jet_pt 600. 800. --sigsel genhtt 0.5 1.5 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$\mu\tau_{h},~800<p_{T}(j)$' --lumi 36.7 --regions hadmu_signal --hist mass_kin --savetag hadmu_jet_pt_800_1200 --sel jet_pt 800. inf --sigsel genhtt 2.5 3.5 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$e\tau_{h},~800<p_{T}(j)$' --lumi 36.7 --regions hadel_signal --hist mass_kin --savetag hadel_jet_pt_800_1200 --sel jet_pt 800. inf --sigsel genhtt 1.5 2.5 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$\tau_{h}\tau_{h},~800<p_{T}(j)$' --lumi 36.7 --regions hadhad_signal --hist mass_kin --savetag hadhad_jet_pt_800_1200 --sel jet_pt 800. inf --sigsel genhtt 0.5 1.5 --dosigrat
 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist evt_kin --savetag hadmu_met120 --sel met_pt 120. inf --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist evt_kin --savetag hadel_met120 --sel met_pt 120. inf --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist evt_kin --savetag hadmu_cr_qcd_met120 --sel met_pt 120. inf --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist evt_kin --savetag hadel_cr_qcd_met120 --sel met_pt 120. inf --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\tau_{h}\tau_{h}$' --lumi 36.7 --regions hadhad_signal --hist evt_kin --savetag hadhad_met120 --sel met_pt 120. inf --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\tau_{h}\tau_{h}~t\bar{t}~CR~\mu$' --lumi 36.7 --regions hadhad_cr_mu --hist evt_kin --savetag hadhad_cr_mu_met120 --sel met_pt 120. inf --dosigrat
 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist evt_kin --savetag hadmu_met120 --sel met_pt 120. inf --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(e)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist evt_kin --savetag hadel_met120 --sel met_pt 120. inf --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist evt_kin --savetag hadmu_cr_qcd_met120 --sel met_pt 120. inf --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(e)$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist evt_kin --savetag hadel_cr_qcd_met120 --sel met_pt 120. inf --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\tau_{h}\tau_{h}~t\bar{t}~CR~\mu$' --lumi 36.7 --regions hadhad_cr_mu --hist evt_kin --savetag hadhad_cr_mu_met120 --sel met_pt 120. inf --dosigrat
 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist evt_kin --savetag hadmu_jet300_350 --sel jet_pt neginf 350. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist evt_kin --savetag hadel_jet300_350 --sel jet_pt neginf 350. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist evt_kin --savetag hadmu_cr_qcd_jet300_350 --sel jet_pt neginf 350. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist evt_kin --savetag hadel_cr_qcd_jet300_350 --sel jet_pt neginf 350. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\tau_{h}\tau_{h}$' --lumi 36.7 --regions hadhad_signal --hist evt_kin --savetag hadhad_jet300_350 --sel jet_pt neginf 350. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\tau_{h}\tau_{h}~t\bar{t}~CR~\mu$' --lumi 36.7 --regions hadhad_cr_mu --hist evt_kin --savetag hadhad_cr_mu_jet300_350 --sel jet_pt neginf 350. --dosigrat
 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist evt_kin --savetag hadmu_jet300_350 --sel jet_pt neginf 350. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(e)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist evt_kin --savetag hadel_jet300_350 --sel jet_pt neginf 350. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist evt_kin --savetag hadmu_cr_qcd_jet300_350 --sel jet_pt neginf 350. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(e)$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist evt_kin --savetag hadel_cr_qcd_jet300_350 --sel jet_pt neginf 350. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\tau_{h}\tau_{h}~t\bar{t}~CR~\mu$' --lumi 36.7 --regions hadhad_cr_mu --hist evt_kin --savetag hadhad_cr_mu_jet300_350 --sel jet_pt neginf 350. --dosigrat
 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist evt_kin --savetag hadmu_jet350_400 --sel jet_pt 350. 400. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist evt_kin --savetag hadel_jet350_400 --sel jet_pt 350. 400. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist evt_kin --savetag hadmu_cr_qcd_jet350_400 --sel jet_pt 350. 400. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist evt_kin --savetag hadel_cr_qcd_jet350_400 --sel jet_pt 350. 400. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\tau_{h}\tau_{h}$' --lumi 36.7 --regions hadhad_signal --hist evt_kin --savetag hadhad_jet350_400 --sel jet_pt 350. 400. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\tau_{h}\tau_{h}~t\bar{t}~CR~\mu$' --lumi 36.7 --regions hadhad_cr_mu --hist evt_kin --savetag hadhad_cr_mu_jet350_400 --sel jet_pt 350. 400. --dosigrat
 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist evt_kin --savetag hadmu_jet350_400 --sel jet_pt 350. 400. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(e)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist evt_kin --savetag hadel_jet350_400 --sel jet_pt 350. 400. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist evt_kin --savetag hadmu_cr_qcd_jet350_400 --sel jet_pt 350. 400. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(e)$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist evt_kin --savetag hadel_cr_qcd_jet350_400 --sel jet_pt 350. 400. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\tau_{h}\tau_{h}~t\bar{t}~CR~\mu$' --lumi 36.7 --regions hadhad_cr_mu --hist evt_kin --savetag hadhad_cr_mu_jet350_400 --sel jet_pt 350. 400. --dosigrat
 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist evt_kin --savetag hadmu_jet400_500 --sel jet_pt 400. 500. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist evt_kin --savetag hadel_jet400_500 --sel jet_pt 400. 500. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist evt_kin --savetag hadmu_cr_qcd_jet400_500 --sel jet_pt 400. 500. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist evt_kin --savetag hadel_cr_qcd_jet400_500 --sel jet_pt 400. 500. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\tau_{h}\tau_{h}$' --lumi 36.7 --regions hadhad_signal --hist evt_kin --savetag hadhad_jet400_500 --sel jet_pt 400. 500. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\tau_{h}\tau_{h}~t\bar{t}~CR~\mu$' --lumi 36.7 --regions hadhad_cr_mu --hist evt_kin --savetag hadhad_cr_mu_jet400_500 --sel jet_pt 400. 500. --dosigrat
 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist evt_kin --savetag hadmu_jet400_500 --sel jet_pt 400. 500. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(e)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist evt_kin --savetag hadel_jet400_500 --sel jet_pt 400. 500. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist evt_kin --savetag hadmu_cr_qcd_jet400_500 --sel jet_pt 400. 500. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(e)$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist evt_kin --savetag hadel_cr_qcd_jet400_500 --sel jet_pt 400. 500. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\tau_{h}\tau_{h}~t\bar{t}~CR~\mu$' --lumi 36.7 --regions hadhad_cr_mu --hist evt_kin --savetag hadhad_cr_mu_jet400_500 --sel jet_pt 400. 500. --dosigrat
 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist evt_kin --savetag hadmu_jet500_600 --sel jet_pt 500. 600. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist evt_kin --savetag hadel_jet500_600 --sel jet_pt 500. 600. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist evt_kin --savetag hadmu_cr_qcd_jet500_600 --sel jet_pt 500. 600. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist evt_kin --savetag hadel_cr_qcd_jet500_600 --sel jet_pt 500. 600. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\tau_{h}\tau_{h}$' --lumi 36.7 --regions hadhad_signal --hist evt_kin --savetag hadhad_jet500_600 --sel jet_pt 500. 600. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\tau_{h}\tau_{h}~t\bar{t}~CR~\mu$' --lumi 36.7 --regions hadhad_cr_mu --hist evt_kin --savetag hadhad_cr_mu_jet500_600 --sel jet_pt 500. 600. --dosigrat
 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist evt_kin --savetag hadmu_jet500_600 --sel jet_pt 500. 600. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(e)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist evt_kin --savetag hadel_jet500_600 --sel jet_pt 500. 600. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist evt_kin --savetag hadmu_cr_qcd_jet500_600 --sel jet_pt 500. 600. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(e)$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist evt_kin --savetag hadel_cr_qcd_jet500_600 --sel jet_pt 500. 600. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\tau_{h}\tau_{h}~t\bar{t}~CR~\mu$' --lumi 36.7 --regions hadhad_cr_mu --hist evt_kin --savetag hadhad_cr_mu_jet500_600 --sel jet_pt 500. 600. --dosigrat
 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist evt_kin --savetag hadmu_jet600_800 --sel jet_pt 600. 800. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist evt_kin --savetag hadel_jet600_800 --sel jet_pt 600. 800. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist evt_kin --savetag hadmu_cr_qcd_jet600_800 --sel jet_pt 600. 800. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist evt_kin --savetag hadel_cr_qcd_jet600_800 --sel jet_pt 600. 800. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\tau_{h}\tau_{h}$' --lumi 36.7 --regions hadhad_signal --hist evt_kin --savetag hadhad_jet600_800 --sel jet_pt 600. 800. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\tau_{h}\tau_{h}~t\bar{t}~CR~\mu$' --lumi 36.7 --regions hadhad_cr_mu --hist evt_kin --savetag hadhad_cr_mu_jet600_800 --sel jet_pt 600. 800. --dosigrat
 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist evt_kin --savetag hadmu_jet600_800 --sel jet_pt 600. 800. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(e)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist evt_kin --savetag hadel_jet600_800 --sel jet_pt 600. 800. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist evt_kin --savetag hadmu_cr_qcd_jet600_800 --sel jet_pt 600. 800. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(e)$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist evt_kin --savetag hadel_cr_qcd_jet600_800 --sel jet_pt 600. 800. --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\tau_{h}\tau_{h}~t\bar{t}~CR~\mu$' --lumi 36.7 --regions hadhad_cr_mu --hist evt_kin --savetag hadhad_cr_mu_jet600_800 --sel jet_pt 600. 800. --dosigrat
 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist evt_kin --savetag hadmu_jet800_1200 --sel jet_pt 800. inf --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist evt_kin --savetag hadel_jet800_1200 --sel jet_pt 800. inf --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist evt_kin --savetag hadmu_cr_qcd_jet800_1200 --sel jet_pt 800. inf --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist evt_kin --savetag hadel_cr_qcd_jet800_1200 --sel jet_pt 800. inf --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\tau_{h}\tau_{h}$' --lumi 36.7 --regions hadhad_signal --hist evt_kin --savetag hadhad_jet800_1200 --sel jet_pt 800. inf --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\tau_{h}\tau_{h}~t\bar{t}~CR~\mu$' --lumi 36.7 --regions hadhad_cr_mu --hist evt_kin --savetag hadhad_cr_mu_jet800_1200 --sel jet_pt 800. inf --dosigrat
 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist evt_kin --savetag hadmu_jet800_1200 --sel jet_pt 800. inf --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(e)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist evt_kin --savetag hadel_jet800_1200 --sel jet_pt 800. inf --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\mu\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadmu_cr_qcd --hist evt_kin --savetag hadmu_cr_qcd_jet800_1200 --sel jet_pt 800. inf --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(e)$' --title '$e\tau_{h}~ QCD~CR$' --lumi 36.7 --regions hadel_cr_qcd --hist evt_kin --savetag hadel_cr_qcd_jet800_1200 --sel jet_pt 800. inf --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var lep_pt --varlabel '$p_{T}(\mu)$' --title '$\tau_{h}\tau_{h}~t\bar{t}~CR~\mu$' --lumi 36.7 --regions hadhad_cr_mu --hist evt_kin --savetag hadhad_cr_mu_jet800_1200 --sel jet_pt 800. inf --dosigrat
 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$\tau_{h}\tau_{h}$' --lumi 36.7 --regions hadhad_signal --hist mass_kin --savetag hadhad_genmatch --sel genhtt 0.5 1.5 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist mass_kin --savetag hadel_genmatch --sel genhtt 1.5 2.5 --dosigrat
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_msd --varlabel '$m_{SD}(jet)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist mass_kin --savetag hadmu_genmatch --sel genhtt 2.5 3.5 --dosigrat

python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist evt_kin --savetag hadmu_lep40_met50 --dosigrat --sel lep_pt 40. inf met_pt 40. inf
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist evt_kin --savetag hadel_lep40_met50 --dosigrat --sel lep_pt 40. inf met_pt 40. inf
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\tau_{h}\tau_{h}$' --lumi 36.7 --regions hadhad_signal --hist evt_kin --savetag hadhad_lep40_met50 --dosigrat --sel lep_pt 40. inf met_pt 40. inf
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist evt_kin --savetag hadmu_lep40_met120 --dosigrat --sel lep_pt 40. inf met_pt 120. inf
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist evt_kin --savetag hadel_lep40_met120 --dosigrat --sel lep_pt 40. inf met_pt 120. inf
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\tau_{h}\tau_{h}$' --lumi 36.7 --regions hadhad_signal --hist evt_kin --savetag hadhad_lep40_met120 --dosigrat --sel lep_pt 40. inf met_pt 120. inf
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist evt_kin --savetag hadmu_lep40_met200 --dosigrat --sel lep_pt 40. inf met_pt 200. inf
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist evt_kin --savetag hadel_lep40_met200 --dosigrat --sel lep_pt 40. inf met_pt 200. inf
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\tau_{h}\tau_{h}$' --lumi 36.7 --regions hadhad_signal --hist evt_kin --savetag hadhad_lep40_met200 --dosigrat --sel lep_pt 40. inf met_pt 200. inf
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist evt_kin --savetag hadmu_lep60_met50 --dosigrat --sel lep_pt 60. inf met_pt 40. inf
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist evt_kin --savetag hadel_lep60_met50 --dosigrat --sel lep_pt 60. inf met_pt 40. inf
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\tau_{h}\tau_{h}$' --lumi 36.7 --regions hadhad_signal --hist evt_kin --savetag hadhad_lep60_met50 --dosigrat --sel lep_pt 60. inf met_pt 40. inf
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist evt_kin --savetag hadmu_lep60_met120 --dosigrat --sel lep_pt 60. inf met_pt 120. inf
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist evt_kin --savetag hadel_lep60_met120 --dosigrat --sel lep_pt 60. inf met_pt 120. inf
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\tau_{h}\tau_{h}$' --lumi 36.7 --regions hadhad_signal --hist evt_kin --savetag hadhad_lep60_met120 --dosigrat --sel lep_pt 60. inf met_pt 120. inf
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\mu\tau_{h}$' --lumi 36.7 --regions hadmu_signal --hist evt_kin --savetag hadmu_lep60_met200 --dosigrat --sel lep_pt 60. inf met_pt 200. inf
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$e\tau_{h}$' --lumi 36.7 --regions hadel_signal --hist evt_kin --savetag hadel_lep60_met200 --dosigrat --sel lep_pt 60. inf met_pt 200. inf
python plot_stack.py --hists ../condor/Oct01/hists_sum --tag Oct01 --var jet_pt --varlabel '$p_{T}(jet)$' --title '$\tau_{h}\tau_{h}$' --lumi 36.7 --regions hadhad_signal --hist evt_kin --savetag hadhad_lep60_met200 --dosigrat --sel lep_pt 60. inf met_pt 200. inf
